using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace SynArmorAAFixMissingGenderWorldModel
{
    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("PatcherSettings", "settings.json", out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (Settings.Value.ArmorTemplateData.Count == 0)
            {
                Console.WriteLine($"Armor addons are not set. Exit..");
                return;
            }

            bool isIgnoreMods = Settings.Value.IgnoreMods.Count > 0;
            var ignoreModsList = Settings.Value.IgnoreMods;

            FormKey defaultRaceFormKey = FormKey.Factory("000019:Skyrim.esm");

            // iterate armors
            foreach (var armorGetterContext in state.LoadOrder.PriorityOrder.Armor().WinningContextOverrides())
            {
                if (isIgnoreMods && ignoreModsList.Contains(armorGetterContext.ModKey)) continue;

                var armorGetter = armorGetterContext.Record;
                // skip invalid
                if (armorGetter == null) continue;
                if (armorGetter.MajorFlags.HasFlag(Armor.MajorFlag.NonPlayable)) continue;
                if (armorGetter.MajorFlags.HasFlag(Armor.MajorFlag.Shield)) continue;
                if (armorGetter.Keywords == null) continue;
                if (armorGetter.BodyTemplate == null) continue;
                if (armorGetter.BodyTemplate.Flags.HasFlag(BodyTemplate.Flag.NonPlayable)) continue;

                var armorTemplateData = Settings.Value.ArmorTemplateData.FirstOrDefault(t => armorGetter.Keywords.Contains(t.Keyword) && t.SlotArmorAddons != null);
                if (armorTemplateData == null) continue;

                foreach (var aaFormlinkGetter in armorGetter.Armature)
                {
                    if (!aaFormlinkGetter.TryResolve(state.LinkCache, out var aa) || aa == null) continue;
                    if (string.IsNullOrWhiteSpace(aa.EditorID)) continue;
                    if (aa.BodyTemplate == null) continue;
                    if (aa.WorldModel == null) continue;
                    if (aa.Race.FormKey != defaultRaceFormKey) continue;

                    if (aa.WorldModel.Female != null
                        && aa.WorldModel.Male != null
                        && !string.IsNullOrWhiteSpace(aa.WorldModel.Female.File)
                        && !string.IsNullOrWhiteSpace(aa.WorldModel.Male.File)
                            ) continue;

                    KeyValuePair<BipedObjectFlag, FormLink<IArmorAddonGetter>> r = new KeyValuePair<BipedObjectFlag, FormLink<IArmorAddonGetter>>();
                    try
                    {
                        r = armorTemplateData.SlotArmorAddons!.First(f => f.Value != null && !f.Value.FormKey.IsNull && aa.BodyTemplate.FirstPersonFlags.HasFlag(f.Key));
                    }
                    catch (InvalidOperationException)
                    {
                        continue;
                    }

                    try
                    {
                        var templateArmorAddonGetter = r.Value.Resolve(state.LinkCache);

                        var aanew = state.PatchMod.ArmorAddons.GetOrAddAsOverride(aa);
                        if (aanew.WorldModel!.Male == null || string.IsNullOrWhiteSpace(aanew.WorldModel.Male!.File))
                        {
                            Console.WriteLine($"Add male path to '{aanew.EditorID}|{aanew.FormKey.ID}' from '{templateArmorAddonGetter.EditorID}|{templateArmorAddonGetter.FormKey.ID}'");

                            aanew.WorldModel.Male = aanew.EditorID!.Contains("hair", StringComparison.InvariantCultureIgnoreCase) && aanew.WorldModel.Female != null && !string.IsNullOrWhiteSpace(aanew.WorldModel.Female.File) ? aanew.WorldModel.Female : new Model() { File = templateArmorAddonGetter.WorldModel!.Male!.File };
                        }
                        if (aanew.WorldModel.Female == null || string.IsNullOrWhiteSpace(aanew.WorldModel.Female!.File))
                        {
                            Console.WriteLine($"Add female path to '{aanew.EditorID}|{aanew.FormKey.ID}' from '{templateArmorAddonGetter.EditorID}|{templateArmorAddonGetter.FormKey.ID}'");

                            aanew.WorldModel.Female = aanew.EditorID!.Contains("hair", StringComparison.InvariantCultureIgnoreCase) && aanew.WorldModel.Male != null && !string.IsNullOrWhiteSpace(aanew.WorldModel.Male.File) ? aanew.WorldModel.Male : new Model() { File = templateArmorAddonGetter.WorldModel!.Female!.File };
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"An error occered. Target AA'{aa.EditorID}|{aa.FormKey.ID}', template AA:'{r.Value.FormKey}'");
                    }
                }
            }
        }
    }
}
